### ISSUE TITLE
Does Kastri have TTS for Android?

### ISSUE THREAD

**Issue by kabiri** [DelphiWorlds/HowTo#2]
Does Kastri have TTS for Android and IOS?

**Comment by DelphiWorlds** [comment]
No, it has the reverse, i.e. Speech Recognition. If you want to request an enhancement to Kastri, please use the [issues section in Kastri](https://github.com/DelphiWorlds/Kastri/issues)

**Comment by DelphiWorlds** [comment]
I've now added TextToSpeech to Kastri: https://github.com/DelphiWorlds/Kastri/tree/master/Demos/TextToSpeech
