### ISSUE TITLE
Do you know where INIntentResponse is defined for IOS?

### ISSUE THREAD

**Issue by kabiri** [DelphiWorlds/HowTo#3]
I have imported the class related to the Cocoa framework UIKit with the name iOSapi.UIKit.pas into Delphi.
In the following line

`TUIKitCompletionHandler = procedure(param1: INIntentResponse) of object;`

declares that INIntentResponse is not defined
[DCC Error] iOSapi.UIKit.pas(2419): E2003 Undeclared identifier: 'INIntentResponse'

Also, iOSapi.Foundation and iOSapi.Security units are referenced circularly. (by SdkTransform tool)
Can you give me some advice?

**Comment by DelphiWorlds** [comment]
I've imported the Intents framework that contains `INIntentResponse` [here](https://github.com/DelphiWorlds/Kastri/blob/master/API/DW.iOSapi.Intents.pas) - you'll find a number of imports for other frameworks in the same folder. You may also find that I have already imported what you need in [DW.iOSapi.UIKit.pas](https://github.com/DelphiWorlds/Kastri/blob/master/API/DW.iOSapi.UIKit.pas), except probably not in this case, since the method you're dealing with appears to be from UIApplicationDelegate, which is incomplete in EMBT's import, and I have not included an import for it

> Also, iOSapi.Foundation and iOSapi.Security units are referenced circularly

If you remove iOSapi.Security from the uses clause of iOSapi.Foundation, which declarations are undefined?

**Comment by kabiri** [comment]
I want to use iOSapi.StoreKit.
If i remove iOSapi.Security from the uses clause of iOSapi.Foundation.
It gets a lot of errors.
[DCC Error] iOSapi.Foundation.pas(237): E2003 Undeclared identifier: 'kCFISO8601DateFormatWithYear'
[DCC Error] iOSapi.Foundation.pas(238): E2003 Undeclared identifier: 'kCFISO8601DateFormatWithMonth'
[DCC Error] iOSapi.Foundation.pas(239): E2003 Undeclared identifier: 'kCFISO8601DateFormatWithWeekOfYear'
[DCC Error] iOSapi.Foundation.pas(240): E2003 Undeclared identifier: 'kCFISO8601DateFormatWithDay'
[DCC Error] iOSapi.Foundation.pas(241): E2003 Undeclared identifier: 'kCFISO8601DateFormatWithTime'
[DCC Error] iOSapi.Foundation.pas(242): E2003 Undeclared identifier: 'kCFISO8601DateFormatWithTimeZone'
[DCC Error] iOSapi.Foundation.pas(244): E2003 Undeclared identifier: 'kCFISO8601DateFormatWithSpaceBetweenDateAndTime'
[DCC Error] iOSapi.Foundation.pas(246): E2003 Undeclared identifier: 'kCFISO8601DateFormatWithDashSeparatorInDate'
[DCC Error] iOSapi.Foundation.pas(248): E2003 Undeclared identifier: 'kCFISO8601DateFormatWithColonSeparatorInTime'
[DCC Error] iOSapi.Foundation.pas(250): E2003 Undeclared identifier: 'kCFISO8601DateFormatWithColonSeparatorInTimeZone'
[DCC Error] iOSapi.Foundation.pas(252): E2003 Undeclared identifier: 'kCFISO8601DateFormatWithFractionalSeconds'
[DCC Error] iOSapi.Foundation.pas(253): E2003 Undeclared identifier: 'kCFISO8601DateFormatWithFullDate'
[DCC Error] iOSapi.Foundation.pas(254): E2003 Undeclared identifier: 'kCFISO8601DateFormatWithFullTime'
[DCC Error] iOSapi.Foundation.pas(256): E2003 Undeclared identifier: 'kCFISO8601DateFormatWithInternetDateTime'
[DCC Error] iOSapi.Foundation.pas(282): E2003 Undeclared identifier: 'kCFNumberFormatterOrdinalStyle'
[DCC Error] iOSapi.Foundation.pas(284): E2003 Undeclared identifier: 'kCFNumberFormatterCurrencyISOCodeStyle'
[DCC Error] iOSapi.Foundation.pas(285): E2003 Undeclared identifier: 'kCFNumberFormatterCurrencyPluralStyle'
[DCC Error] iOSapi.Foundation.pas(287): E2003 Undeclared identifier: 'kCFNumberFormatterCurrencyAccountingStyle'
[DCC Error] iOSapi.Foundation.pas(1737): E2003 Undeclared identifier: 'NSObjectClass'
[DCC Error] iOSapi.Foundation.pas(1737): E2205 Interface type required
[DCC Error] iOSapi.Foundation.pas(1787): E2003 Undeclared identifier: 'NSObject'
[DCC Error] iOSapi.Foundation.pas(2065): E2514 Type parameter 'C' must support interface 'IObjectiveCClass'
[DCC Error] iOSapi.Foundation.pas(2070): E2005 'NSObjectClass' is not a type identifier
[DCC Error] iOSapi.Foundation.pas(2070): E2205 Interface type required
[DCC Error] iOSapi.Foundation.pas(2076): E2005 'NSObject' is not a type identifier
[DCC Error] iOSapi.Foundation.pas(2093): E2514 Type parameter 'C' must support interface 'IObjectiveCClass'
[DCC Error] iOSapi.Foundation.pas(2098): E2005 'NSObjectClass' is not a type identifier
[DCC Error] iOSapi.Foundation.pas(2098): E2205 Interface type required
[DCC Error] iOSapi.Foundation.pas(2104): E2005 'NSObject' is not a type identifier
[DCC Error] iOSapi.Foundation.pas(2115): E2514 Type parameter 'C' must support interface 'IObjectiveCClass'
[DCC Error] iOSapi.Foundation.pas(2120): E2005 'NSObjectClass' is not a type identifier
[DCC Error] iOSapi.Foundation.pas(2120): E2205 Interface type required
[DCC Error] iOSapi.Foundation.pas(2124): E2005 'NSObject' is not a type identifier
[DCC Error] iOSapi.Foundation.pas(2212): E2514 Type parameter 'C' must support interface 'IObjectiveCClass'
[DCC Error] iOSapi.Foundation.pas(2217): E2005 'NSObjectClass' is not a type identifier
[DCC Error] iOSapi.Foundation.pas(2217): E2205 Interface type required
[DCC Error] iOSapi.Foundation.pas(2221): E2005 'NSObject' is not a type identifier
[DCC Error] iOSapi.Foundation.pas(2227): E2514 Type parameter 'C' must support interface 'IObjectiveCClass'
[DCC Error] iOSapi.Foundation.pas(2246): E2005 'NSObjectClass' is not a type identifier
[DCC Error] iOSapi.Foundation.pas(2246): E2205 Interface type required
[DCC Error] iOSapi.Foundation.pas(2267): E2005 'NSObject' is not a type identifier
[DCC Error] iOSapi.Foundation.pas(2388): E2005 'NSObject' is not a type identifier
[DCC Error] iOSapi.Foundation.pas(2392): E2005 'NSObject' is not a type identifier
[DCC Error] iOSapi.Foundation.pas(2395): E2005 'NSObject' is not a type identifier
[DCC Error] iOSapi.Foundation.pas(2398): E2005 'NSObject' is not a type identifier
[DCC Error] iOSapi.Foundation.pas(2402): E2005 'NSObject' is not a type identifier
[DCC Error] iOSapi.Foundation.pas(2405): E2005 'NSObject' is not a type identifier
[DCC Error] iOSapi.Foundation.pas(2413): E2514 Type parameter 'C' must support interface 'IObjectiveCClass'
[DCC Error] iOSapi.Foundation.pas(2418): E2005 'NSObjectClass' is not a type identifier
[DCC Error] iOSapi.Foundation.pas(2418): E2205 Interface type required
[DCC Error] iOSapi.Foundation.pas(2444): E2005 'NSObject' is not a type identifier
[DCC Error] iOSapi.Foundation.pas(2531): E2514 Type parameter 'C' must support interface 'IObjectiveCClass'
[DCC Error] iOSapi.Foundation.pas(2536): E2005 'NSObjectClass' is not a type identifier
[DCC Error] iOSapi.Foundation.pas(2536): E2205 Interface type required
[DCC Error] iOSapi.Foundation.pas(2548): E2005 'NSObject' is not a type identifier
[DCC Error] iOSapi.Foundation.pas(2564): E2514 Type parameter 'C' must support interface 'IObjectiveCClass'
[DCC Error] iOSapi.Foundation.pas(2630): E2514 Type parameter 'C' must support interface 'IObjectiveCClass'
[DCC Error] iOSapi.Foundation.pas(2635): E2005 'NSObjectClass' is not a type identifier
[DCC Error] iOSapi.Foundation.pas(2635): E2205 Interface type required
[DCC Error] iOSapi.Foundation.pas(2647): E2005 'NSObject' is not a type identifier
[DCC Error] iOSapi.Foundation.pas(2666): E2514 Type parameter 'C' must support interface 'IObjectiveCClass'
[DCC Error] iOSapi.Foundation.pas(2671): E2005 'NSObjectClass' is not a type identifier
[DCC Error] iOSapi.Foundation.pas(2671): E2205 Interface type required
[DCC Error] iOSapi.Foundation.pas(2680): E2005 'NSObject' is not a type identifier
[DCC Error] iOSapi.Foundation.pas(2727): E2514 Type parameter 'C' must support interface 'IObjectiveCClass'
[DCC Error] iOSapi.Foundation.pas(2750): E2514 Type parameter 'C' must support interface 'IObjectiveCClass'
[DCC Fatal Error] iOSapi.Foundation.pas(2750): E2226 Compilation terminated; too many errors


The SdkTransform tool has a lot of errors.
For example, it has included this somewhere:
`   SEL = SEL *;
    PSEL = ^SEL;
`
which has an error

**Comment by DelphiWorlds** [comment]
> [DCC Error] iOSapi.Foundation.pas(237): E2003 Undeclared identifier: 'kCFISO8601DateFormatWithYear'

Not sure why there would be this error. `kCFISO8601DateFormatWithYear` is part of the `CoreFoundation` framework in iOS (iOS SDK 10 and higher). I'm assuming you are trying to import `iOSapi.Foundation` with SDKTransform, and it is including this reference in error.

You may be better off working out what is missing from `iOSapi.Foundation` that ships with Delphi, and rather than trying to use a complete import, just add the parts that you need, like I have done with [`DW.iOSapi.Foundation`](https://github.com/DelphiWorlds/Kastri/blob/master/API/DW.iOSapi.Foundation.pas). There will be times however, when you will need to redeclare a reference because it has methods that are missing from the one that ships with Delphi
