### ISSUE TITLE
Read NFC tag in android 12

### ISSUE THREAD

**Issue by samuelsoarees** [DelphiWorlds/HowTo#4]
I made download from new version of Kastri, because my app in android 12 raise a exception about FLAG_IMMUTABLE. 

I try to use the demo to test the new version of NFCReader, but the app vibrates and dont capture the tag, and dont call the method NFCReaderResultHandler. 

Im used Delphi 11.

**Comment by DelphiWorlds** [comment]
I've pushed a fix to `DW.NFC.Android.pas`. In future, please report issues with Kastri to the [Kastri issues]( https://github.com/DelphiWorlds/Kastri/issues) section
