### ISSUE TITLE
complex code

### ISSUE THREAD

**Issue by birbilis** [DelphiWorlds/HowTo#6]
at
https://github.com/DelphiWorlds/HowTo/blob/fab87c2820935c886b4f7ca75969010d1699fe38/Demos/OpenURL/Unit1.pas#L48
it could have used StrToNSUrl from Macapi.Helpers (Delphi 12.2, not sure when it was introduced)

```
function StrToNSUrl(const AStr: string): NSUrl;
begin
  Result := TNSUrl.Wrap(TNSUrl.OCClass.URLWithString(StrToNSStr(AStr)));
end;
```

**Comment by birbilis** [comment]
if not available for older Delphi's could have that as function in that code to make it look simpler

**Comment by DelphiWorlds** [comment]
Done, thanks!

**Comment by birbilis** [comment]
you're welcome
btw, I have an implementation for all platforms here:
https://github.com/Zoomicon/Zoomicon.Helpers.FMX.Delphi/blob/main/Source/Zoomicon.Helpers.FMX.Forms.ApplicationHelper.pas
fixed to work on iOS based on this sample

a question I have though is will it work for older iOS?
I think in Kastri issue chat on that they say at iOS 10 the other open (that is missing from Delphi's UIApplication) was introduced - does Apple handle this like Google does for older versions with Jetpack, or will it fail when called and thus I also need to do OS version check in iOS and call the older openURL method maybe?

**Comment by DelphiWorlds** [comment]
> a question I have though is will it work for older iOS?

It won't work on iOS 9 or earlier, however as of February 2024, only 11 percent of Apple devices accessing the Apple App Store are running iOS versions earlier than iOS 16. Extrapolating from that, I'd guess that less than 1% are using iOS 9 or earlier - it's not worth catering for so few devices with versions that old.
